name: Django CI Test

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']  # based on Django 4.2 (LTS) + 5.1 + 5.2 (LTS)

    steps:
    - name: Install LDAP deps
      run: |
        sudo apt-get update
        sudo apt install -y libldap2-dev libsasl2-dev

    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip

    - name: Cache uv and tox
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/uv
          .tox
        key: ${{ runner.os }}-py${{ matrix.python-version }}-uv-tox-${{ hashFiles('**/tox.ini', '**/pyproject.toml', '**/poetry.lock', '**/requirements*.txt', '**/setup.cfg', '**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-py${{ matrix.python-version }}-uv-tox-

    - name: Install Dependencies
      run: |
        python -m pip install uv tox-uv tox-gh

    - name: Run Tests
      run: tox
